### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [AngelaDmytreno/responsive-grid-template#1]
1)
Проверьте межстрочный интервал, нет соответствия
![image](https://user-images.githubusercontent.com/8464662/95505337-db20f480-09b6-11eb-902d-bfbbf598f71d.png)
и здесь не совсем совпадает
![image](https://user-images.githubusercontent.com/8464662/95505395-eecc5b00-09b6-11eb-937d-02f54b0eb36a.png)

2)
нет совпадения контейнера для всех секций
![image](https://user-images.githubusercontent.com/8464662/95505491-128fa100-09b7-11eb-9fb3-81bd90abf02d.png)

3)
цвет, фон не соответствуют макету
![image](https://user-images.githubusercontent.com/8464662/95505528-23401700-09b7-11eb-9e76-d3a4c513bd5c.png)
![image](https://user-images.githubusercontent.com/8464662/95505550-30f59c80-09b7-11eb-87de-9b8a50f82665.png)

4)
в данной секции нет вообще никакого соответствия макету
![image](https://user-images.githubusercontent.com/8464662/95505569-38b54100-09b7-11eb-9c44-272a3a6d5101.png)

5)
код невалиден
![image](https://user-images.githubusercontent.com/8464662/95505613-4ff42e80-09b7-11eb-810d-693aa059bb55.png)

6)
стиль невалиден
![image](https://user-images.githubusercontent.com/8464662/95505643-626e6800-09b7-11eb-86f3-11f08ff3ac2a.png)

7)
в сдаваемом проекте не должно быть мусора и необоснованных пустых строк
![image](https://user-images.githubusercontent.com/8464662/95505695-75813800-09b7-11eb-8ec5-c640b430f6aa.png)

**Comment by Alecto** [comment]
1 - меню не исправили
2 - не исправили
3 - наведение не исправили

**Comment by Alecto** [comment]
1 - был неправл, межсимвольный.
2 - не исправлено
3 - не исправлено

**Comment by Alecto** [comment]
2 - исправили, не туда посмотрел.

8)
некорректное отображение формы на всех разрешениях
![image](https://user-images.githubusercontent.com/8464662/95688006-b4a9c600-0c0f-11eb-8d95-b9c1feee3a55.png)
![image](https://user-images.githubusercontent.com/8464662/95688008-b96e7a00-0c0f-11eb-8fd1-f31333e7ced6.png)
![image](https://user-images.githubusercontent.com/8464662/95688009-bd020100-0c0f-11eb-9699-d3d09fd978d5.png)

**Comment by Alecto** [comment]
8)
некорректное отображение формы на всех разрешениях
не исправлено.

9)
требования к высоте не выполнены
![image](https://user-images.githubusercontent.com/8464662/95907248-e489d280-0da3-11eb-8211-5cf1b1120ee8.png)

10)
требования к шрифту не выполнены
![image](https://user-images.githubusercontent.com/8464662/95907293-f53a4880-0da3-11eb-8697-54dd0bc94eec.png)

11)
выравнивание неправильно
![image](https://user-images.githubusercontent.com/8464662/95907341-0d11cc80-0da4-11eb-846f-c0475cc10323.png)

12)
неправильные отступы, проверьте для всех разрешений
![image](https://user-images.githubusercontent.com/8464662/95907442-3a5e7a80-0da4-11eb-8c74-ebc6a11e800c.png)
![image](https://user-images.githubusercontent.com/8464662/95907432-33d00300-0da4-11eb-8ddf-70792ddb61a4.png)

**Comment by Alecto** [comment]
11)
неверный цвет плейсхолдера, белый должен быть при вводе текста, у вас он белый на ховере.
если непонятно поведение из макета, посмотрите шаблон.
![image](https://user-images.githubusercontent.com/8464662/96040232-9e4f7480-0e72-11eb-9b97-ac1b5ff1dd5d.png)

12)
неверное положение разделителя, проверьте для всех разрешений + отступы разделителя
![image](https://user-images.githubusercontent.com/8464662/96040428-ec647800-0e72-11eb-9f2d-fb3276988099.png)

13)
невалидный стиль
![image](https://user-images.githubusercontent.com/8464662/96040547-29c90580-0e73-11eb-972a-cb3d23293a9a.png)

**Comment by AngelaDmytreno** [comment]
Вух,наконец-то))

чт, 15 окт. 2020 г. в 15:14, Andrey <notifications@github.com>:
